### ISSUE TITLE
Statusbar disappears

### ISSUE THREAD

**Issue by vespino** [dcousens/cordova-plugin-statusbar-dev#1]
I have tested your plugin, but the statusbar disappears:

![img_2098](https://cloud.githubusercontent.com/assets/6991325/8132058/419963a0-111f-11e5-8bff-11d8f575b546.PNG)

This is the code I'm using:
`<gap:plugin name="cordova-plugin-statusbar-dev" source="npm" />`

StatusBar.backgroundColorByHexString("#235398");

**Comment by vespino** [comment]
Problem solved using the following:

StatusBar.overlaysWebView(false);
StatusBar.backgroundColorByHexString("#235398");

**Comment by dcousens** [comment]
@vespino sorry this plugin was for internal testing only.  I only exposed it through `npm` so I could test it on `phonegap`.
I'll be unpublishing it soon,  please use `cordova-plugin-statusbar-dev` instead.
